### ISSUE TITLE
Can't sign up

### ISSUE THREAD

**Issue by lfbarragan** [jesusjackson/forum#1]
After doing bundle install, creating the db and creating the database.yml I started the server and tried to create a user but got this error:

<img width="1438" alt="screen shot 2017-01-30 at 13 22 29" src="https://cloud.githubusercontent.com/assets/354342/22422201/e12bc0e2-e6f3-11e6-9016-d3f9a05f4ba5.png">

**Comment by lfbarragan** [comment]
Here is the log in case it helps:

`
Started POST "/users" for 127.0.0.1 at 2017-01-30 13:48:03 +0200
Processing by Devise::RegistrationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"NxhqqWhmJEVEy6kjV2WOPCxSCz2EVbzjqkfQFmGhLstP7yPl4rcCaZPsgCoLz9t8FUW4J0/YaxDOSyc4Nfl6Rg==", "user"=>{"email"=>"luis@test.com", "username"=>"luis", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
Unpermitted parameter: username
   (0.2ms)  BEGIN
  User Exists (0.8ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "luis@test.com"], ["LIMIT", 1]]
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "luis@test.com"], ["LIMIT", 1]]
  SQL (0.8ms)  INSERT INTO "users" ("created_at", "updated_at", "email", "encrypted_password") VALUES ($1, $2, $3, $4) RETURNING "id"  [["created_at", 2017-01-30 11:48:03 UTC], ["updated_at", 2017-01-30 11:48:03 UTC], ["email", "luis@test.com"], ["encrypted_password", "$2a$11$pfp.YccVkZ9gaJrk9/AZRuQcSFa72o.UgjJjimiNwJ4L1FGg/1Jya"]]
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 130ms (ActiveRecord: 2.0ms)
`

**Comment by jesusjackson** [comment]
I'm sorry Luis, It was an experiment I was doing with sign in with both username and email. And I had forgotten to remove the column. Now I've included a migration to remove it and removed the field from the views as well.

**Comment by lfbarragan** [comment]
ok, it seems to be working now
